import { Governorate } from '@libas/shared';

export const GOVERNORATE_LABELS: Record<Governorate, string> = {
  [Governorate.ARIANA]: 'Ariana',
  [Governorate.BEJA]: 'Béja',
  [Governorate.BEN_AROUS]: 'Ben Arous',
  [Governorate.BIZERTE]: 'Bizerte',
  [Governorate.GABES]: 'Gabès',
  [Governorate.GAFSA]: 'Gafsa',
  [Governorate.JENDOUBA]: 'Jendouba',
  [Governorate.KAIROUAN]: 'Kairouan',
  [Governorate.KASSERINE]: 'Kasserine',
  [Governorate.KEBILI]: 'Kébili',
  [Governorate.KEF]: 'Le Kef',
  [Governorate.MAHDIA]: 'Mahdia',
  [Governorate.MANOUBA]: 'Manouba',
  [Governorate.MEDENINE]: 'Médenine',
  [Governorate.MONASTIR]: 'Monastir',
  [Governorate.NABEUL]: 'Nabeul',
  [Governorate.SFAX]: 'Sfax',
  [Governorate.SIDI_BOUZID]: 'Sidi Bouzid',
  [Governorate.SILIANA]: 'Siliana',
  [Governorate.SOUSSE]: 'Sousse',
  [Governorate.TATAOUINE]: 'Tataouine',
  [Governorate.TOZEUR]: 'Tozeur',
  [Governorate.TUNIS]: 'Tunis',
  [Governorate.ZAGHOUAN]: 'Zaghouan',
};
